services:
  - type: web
    name: pdf-merger
    env: node
    plan: free

    buildCommand: |
      apt-get update && apt-get install -y libreoffice
      npm install

    startCommand: node src/server.js